spring:
  application:
    name: E-Commerce2

  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce_db2
    username: postgres
    password: akbar_123456789
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
  security:
    user:
      roles: ADMIN
      name: admin
      password: 123

server:
  port: 8083
  error:
    include-message: always
    include-binding-errors: always

jwt:
  secret: "5367566B59703373367639792F423F4528482B4D6251655468576D5A71347437"
  expiration: 86400000

logging:
  level:
    uz.pdp: DEBUG
    org.springframework.security: DEBUG
